[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
clap = { version = "4", features = ["derive"] }
crossbeam-channel = "0.5"
prost = "0.13"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tonic = "0.12"

[lints.clippy]
too_many_arguments = "allow"

[build-dependencies]
tonic-build = "0.12"
